services: 
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    
  
      